[project]
name = "battle-city-clone"
version = "0.1.0"
description = "Just a Battle City (NES) clone"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black",
    "flake8",
    "mypy",
    "pygame",
    "pytest",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
]
